### ISSUE TITLE
[Bug] Ollama Provider not work

### ISSUE THREAD

**Issue by wei840222** [kennethreitz/simplemind#48]
```python
import simplemind as sm
from simplemind.providers.ollama import Ollama

sm.settings.DEFAULT_LLM_PROVIDER = "ollama"
Ollama.DEFAULT_MODEL = "llama3.1"

print(sm.generate_text("hi"))
```
I using this code to run quickstart with ollama but I got some error message like this.
```
Traceback (most recent call last):
  File "/home/wei84/workspace/ollama/play-simplemind/hello.py", line 12, in <module>
    main()
  File "/home/wei84/workspace/ollama/play-simplemind/hello.py", line 8, in main
    print(sm.generate_text("hi"))
  File "/home/wei84/workspace/ollama/play-simplemind/.venv/lib/python3.10/site-packages/simplemind/__init__.py", line 123, in generate_text
    return provider.generate_text(prompt=prompt, llm_model=llm_model, **kwargs)
  File "/home/wei84/workspace/ollama/play-simplemind/.venv/lib/python3.10/site-packages/simplemind/logging.py", line 16, in wrapper
    return func(*args, **kwargs)
  File "/home/wei84/workspace/ollama/play-simplemind/.venv/lib/python3.10/site-packages/simplemind/providers/ollama.py", line 103, in generate_text
    response = self.client.chat(
TypeError: 'Chat' object is not callable
```

It seems ollama also using openai.OpenAI as client
https://github.com/kennethreitz/simplemind/blob/main/simplemind/providers/ollama.py#L38

but the implementation is different between the two providers
https://github.com/kennethreitz/simplemind/blob/main/simplemind/providers/ollama.py#L95
https://github.com/kennethreitz/simplemind/blob/main/simplemind/providers/openai.py#L201

**Comment by wei840222** [comment]
I'd be happy to contribute a pr to this if you'd like.

**Comment by kennethreitz** [comment]
interesting @wei840222, i cannot reproduce

**Comment by wei840222** [comment]
my simplemind version is `0.2.4`
and the openai dependencie version is `1.54.4`

**Comment by bertbesser** [comment]
I also have this, in a fresh venv with:
```
aiohappyeyeballs                         2.4.3
aiohttp                                  3.11.7
aiosignal                                1.3.1
annotated-types                          0.7.0
anyio                                    4.6.2.post1
asttokens                                2.4.1
attrs                                    24.2.0
certifi                                  2024.8.30
charset-normalizer                       3.4.0
click                                    8.1.7
decorator                                5.1.1
Deprecated                               1.2.15
distro                                   1.9.0
docstring_parser                         0.16
executing                                2.1.0
frozenlist                               1.5.0
googleapis-common-protos                 1.66.0
h11                                      0.14.0
httpcore                                 1.0.7
httpx                                    0.27.2
idna                                     3.10
importlib_metadata                       8.5.0
instructor                               1.6.4
ipython                                  8.29.0
jedi                                     0.19.2
Jinja2                                   3.1.4
jiter                                    0.6.1
logfire                                  2.4.1
markdown-it-py                           3.0.0
MarkupSafe                               3.0.2
matplotlib-inline                        0.1.7
mdurl                                    0.1.2
multidict                                6.1.0
openai                                   1.55.0
opentelemetry-api                        1.28.2
opentelemetry-exporter-otlp-proto-common 1.28.2
opentelemetry-exporter-otlp-proto-http   1.28.2
opentelemetry-instrumentation            0.49b2
opentelemetry-proto                      1.28.2
opentelemetry-sdk                        1.28.2
opentelemetry-semantic-conventions       0.49b2
packaging                                24.2
parso                                    0.8.4
pexpect                                  4.9.0
pip                                      24.2
prompt_toolkit                           3.0.48
propcache                                0.2.0
protobuf                                 5.28.3
ptyprocess                               0.7.0
pure_eval                                0.2.3
pydantic                                 2.10.1
pydantic_core                            2.27.1
pydantic-settings                        2.6.1
Pygments                                 2.18.0
python-dotenv                            1.0.1
requests                                 2.32.3
rich                                     13.9.4
shellingham                              1.5.4
simplemind                               0.2.4
six                                      1.16.0
sniffio                                  1.3.1
stack-data                               0.6.3
tenacity                                 9.0.0
tqdm                                     4.67.0
traitlets                                5.14.3
typer                                    0.13.1
typing_extensions                        4.12.2
urllib3                                  2.2.3
wcwidth                                  0.2.13
wrapt                                    1.17.0
yarl                                     1.18.0
zipp                                     3.21.0
```

**Comment by bertbesser** [comment]
This OpenAI object seems to be the issue:
![image](https://github.com/user-attachments/assets/a75a205f-822a-4712-82a5-2fda809c314b)

**Comment by wei840222** [comment]
@bertbesser @kennethreitz I prepare a fix version u can try by this
```bash
uv init .
uv add 'simplemind[full]' git+https://github.com/wei840222/simplemind@main
```

```python
import simplemind as sm
from simplemind.providers.ollama import Ollama

sm.settings.DEFAULT_LLM_PROVIDER = "ollama"
Ollama.DEFAULT_MODEL = "llama3.1"

print(sm.generate_text(prompt="hi"))
```

**Comment by kennethreitz** [comment]
This should be prepared in 'main' now. /cc @wei840222

**Comment by kennethreitz** [comment]
let me know if it fixes it for you

**Comment by bertbesser** [comment]
It does. Thanks for the quick fix! 💪
